## Ejercicios Numpy 

#### 1. Crea una matriz 4*4 rellena con el valor 0.5

In [ ]:
import numpy as np

matriz = np.full((4, 4), 0.5)

print(matriz)


[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 2. Crea una matriz 6*6 con unos en los bordes y 0 en el interior (utilizando slicing)

In [3]:
import numpy as np

matriz = np.zeros((6, 6))

matriz[0, :] = 1        
matriz[-1, :] = 1       
matriz[:, 0] = 1       
matriz[:, -1] = 1      

print(matriz)


[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 3. Crea una matriz de numpy 3*2 a partir de una lista de listas de números float

In [4]:
import numpy as np

lista = [[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]]

matriz = np.array(lista)

print(matriz)

[[1.1 2.2]
 [3.3 4.4]
 [5.5 6.6]]


#### 4. Divide entre 4 los valores de la columna 1

In [5]:
import numpy as np

lista = [[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]]

matriz = np.array(lista)

matriz[:, 1] = matriz[:, 1] / 4

print(matriz)


[[1.1  0.55]
 [3.3  1.1 ]
 [5.5  1.65]]


#### 5. Calcula la media de los elementos de las primeras dos primeras filas

In [6]:
import numpy as np

lista = [[1.1, 2.2], [3.3, 4.4], [5.5, 6.6]]

matriz = np.array(lista)

media = np.mean(matriz[:2])  

print(media)


2.75


#### 6. Crea una matriz aletoria de 4*4 con valores en [0, 1) 

El módulo <code>random</code> de numpy sirve para generar números aleatorios. En él tenemos varias funciones entre ellas <a href="https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html">rand</a>



In [7]:
import numpy as np

matriz_aleatoria = np.random.rand(4, 4)

print(matriz_aleatoria)


[[0.11879695 0.67714871 0.17187971 0.88185673]
 [0.60187021 0.11801084 0.12063867 0.71161374]
 [0.27324641 0.6518622  0.92732969 0.9463253 ]
 [0.74124629 0.45550391 0.48131396 0.24990372]]


#### 7.  Muestra la suma, media y desviación de los elementos de la matriz del ejercicio 1 

In [2]:

import numpy as np

matriz = np.full((4, 4), 0.5)

suma = np.sum(matriz)

media = np.mean(matriz)

desviacion = np.std(matriz)

print(f"Suma: {suma}")
print(f"Media: {media}")
print(f"Desviación estándar: {desviacion}")


Suma: 8.0
Media: 0.5
Desviación estándar: 0.0


#### 8. Ordena por filas la matriz del ejercicio 1

In [1]:

import numpy as np

matriz = np.full((4, 4), 0.5)

matriz_ordenada = np.sort(matriz, axis=1)

print(matriz_ordenada)


[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


#### 9. Multiplica las matrices del ejercio 1 y 6

In [4]:
import numpy as np

matriz = np.full((4, 4), 0.5)

matriz_aleatoria = np.random.rand(4, 4)

resultado = np.dot(matriz, matriz_aleatoria)

print("Matriz con valores 0.5:")
print(matriz)

print("\nMatriz aleatoria:")
print(matriz_aleatoria)

print("\nResultado de la multiplicación:")
print(resultado)


Matriz con valores 0.5:
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]

Matriz aleatoria:
[[0.15573295 0.00809152 0.11313801 0.61246795]
 [0.01835289 0.10720832 0.42116048 0.75136881]
 [0.25209999 0.50089344 0.28775613 0.55083046]
 [0.32125948 0.97758801 0.11760707 0.60023269]]

Resultado de la multiplicación:
[[0.37372265 0.79689064 0.46983084 1.25744995]
 [0.37372265 0.79689064 0.46983084 1.25744995]
 [0.37372265 0.79689064 0.46983084 1.25744995]
 [0.37372265 0.79689064 0.46983084 1.25744995]]


#### 10. Prueba a concatenar las matrices de los ejercicios 1 y 6 en vertical y horizontal

Echa un vistazo al apartado 2 del siguiente <a href="https://rmoralesdelgado.com/all/numpy-concatenate-r_-c_/"> link </a> donde explica el uso de <a href="https://numpy.org/doc/stable/reference/generated/numpy.c_.html">numpy.c_ </a> y <a href="https://numpy.org/doc/stable/reference/generated/numpy.r_.html">numpy.r_</a>

Fíjate también en <code>%%timeit</code> que se usa en Jupyter notebooks para medir el tiempo de ejecución de un bloque de código

In [5]:
import numpy as np

matriz = np.full((4, 4), 0.5)

matriz_aleatoria = np.random.rand(4, 4)

concat_horizontal = np.hstack((matriz, matriz_aleatoria))

concat_vertical = np.vstack((matriz, matriz_aleatoria))

concat_horizontal_c = np.c_[matriz, matriz_aleatoria]

concat_vertical_r = np.r_[matriz, matriz_aleatoria]

print("Concatenación Horizontal:")
print(concat_horizontal)

print("\nConcatenación Vertical:")
print(concat_vertical)

print("\nConcatenación Horizontal con np.c_:")
print(concat_horizontal_c)

print("\nConcatenación Vertical con np.r_:")
print(concat_vertical_r)



Concatenación Horizontal:
[[0.5        0.5        0.5        0.5        0.34280036 0.5198558
  0.63487627 0.12065119]
 [0.5        0.5        0.5        0.5        0.9196602  0.32385692
  0.17821532 0.26549533]
 [0.5        0.5        0.5        0.5        0.3793852  0.45167561
  0.74109288 0.42927601]
 [0.5        0.5        0.5        0.5        0.30361926 0.39391909
  0.80562634 0.42035801]]

Concatenación Vertical:
[[0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.5        0.5        0.5        0.5       ]
 [0.34280036 0.5198558  0.63487627 0.12065119]
 [0.9196602  0.32385692 0.17821532 0.26549533]
 [0.3793852  0.45167561 0.74109288 0.42927601]
 [0.30361926 0.39391909 0.80562634 0.42035801]]

Concatenación Horizontal con np.c_:
[[0.5        0.5        0.5        0.5        0.34280036 0.5198558
  0.63487627 0.12065119]
 [0.5        0.5        0.5        0.5        0.9196602  0.32385692
  0